/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#aea9b6",
        "on-error": "#490013",
        "on-primary-fixed-variant": "#006266",
        "on-tertiary-fixed": "#33002d",
        "primary": "#a1faff",
        "primary-dim": "#00e5ee",
        "tertiary-fixed-dim": "#ff68e3",
        "surface-container-lowest": "#000000",
        "tertiary": "#ff59e3",
        "secondary-container": "#591adc",
        "inverse-on-surface": "#57535f",
        "inverse-primary": "#006a6e",
        "on-secondary-fixed": "#3b00a0",
        "background": "#0f0d16",
        "error-dim": "#d73357",
        "on-background": "#f5eefc",
        "surface-tint": "#a1faff",
        "outline-variant": "#494651",
        "secondary-fixed-dim": "#cabaff",
        "error-container": "#a70138",
        "surface-container": "#1b1823",
        "on-tertiary": "#42003a",
        "tertiary-container": "#ff05e5",
        "on-primary-container": "#00575b",
        "surface-dim": "#0f0d16",
        "error": "#ff6e84",
        "primary-fixed-dim": "#00e5ee",
        "tertiary-fixed": "#ff85e4",
        "on-error-container": "#ffb2b9",
        "on-secondary": "#25006b",
        "secondary": "#a68cff",
        "on-secondary-fixed-variant": "#591bdc",
        "secondary-fixed": "#d8caff",
        "surface-bright": "#2d2a39",
        "on-primary-fixed": "#004346",
        "outline": "#78737f",
        "primary-fixed": "#00f4fe",
        "surface-container-low": "#14121c",
        "surface-container-high": "#211e2a",
        "inverse-surface": "#fdf7ff",
        "on-secondary-container": "#e4daff",
        "secondary-dim": "#7e51ff",
        "tertiary-dim": "#ff59e3",
        "surface-container-highest": "#272431",
        "on-tertiary-fixed-variant": "#6d0061",
        "surface-variant": "#272431",
        "on-surface": "#f5eefc",
        "on-primary": "#006165",
        "surface": "#0f0d16",
        "primary-container": "#00f4fe",
        "on-tertiary-container": "#1b0017"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
